services:
  server:
    image: opensign/opensignserver:docker_beta
    container_name: OpenSignServer-container
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=production
      - SERVER_URL=${HOST:-https://localhost:3001/app}
    networks:
      - app-network
  mongo:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network
  client:
    image: opensign/opensign:docker_beta
    container_name: OpenSign-container
    env_file: .env
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network
  caddy:
    image: caddy:latest
    container_name: caddy-container
    ports:
      - "3001:3001"
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    environment:
      - HOST=${HOST:-localhost:3001}
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  web-root:
  caddy_data:
  caddy_config:
